[package]
name = "wasm-tree"
version = "0.1.0"
authors = ["Nuria <nuria@codegram.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.50"
rand = { version = "0.6.5", features = ["wasm-bindgen"] }